"""Build the per-phrase timing manifest (A16 / issue #269).

One entry per (combination, cadence) — numbers + techniques renderings
side by side, per-token onset/end times for both vocabularies, and the
measured vocab offset that lets the RhythmSpine derive one vocab's
timing from the other's.

Reads the shipped `src/audio/voiceAssets/phraseManifest.ts` (which
already carries wordMarks from the envelope/whisper pipeline — see the
`cadence-lab` skill) and emits:

  * `src/audio/voiceAssets/phraseTimingManifest.ts` — the compiled
    manifest (typed, DO NOT EDIT header).
  * `tools/analysis/reports/phrase-timing-audit.json` — coverage report
    listing every (combination, cadence) that has at least one vocab
    with `wordMarksSource: "none"` (candidate for re-render).

Usage:
    F:/voice-tools/venv/Scripts/python.exe tools/voice/build_phrase_timing.py
        [--repo-root <dir>]

Dependencies: stdlib only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

PHRASE_BLOCK = re.compile(
    r"\{\s*cueId:\s*\"(?P<cueId>[^\"]+)\","
    r"[\s\S]*?combination:\s*\"(?P<combo>[^\"]+)\","
    r"[\s\S]*?cadence:\s*\"(?P<cadence>[^\"]+)\","
    r"[\s\S]*?vocabulary:\s*\"(?P<vocab>[^\"]+)\","
    r"[\s\S]*?performance:\s*\"(?P<perf>[^\"]+)\","
    r"[\s\S]*?tokens:\s*(?P<tokens>\[[^\]]*\]),"
    r"[\s\S]*?durationMs:\s*(?P<dur>\d+),"
    r"[\s\S]*?wordMarks:\s*(?P<marks>\[[^\]]*\]),"
    r"(?:[\s\S]*?wordMarksSource:\s*\"(?P<source>[^\"]+)\",)?"
)


def load_phrases(path: str) -> List[dict]:
    text = open(path, encoding="utf-8").read()
    rows: List[dict] = []
    for m in PHRASE_BLOCK.finditer(text):
        rows.append({
            "cueId": m["cueId"],
            "combination": m["combo"],
            "cadence": m["cadence"],
            "vocabulary": m["vocab"],
            "performance": m["perf"],
            "tokens": json.loads(m["tokens"]),
            "durationMs": int(m["dur"]),
            "wordMarks": json.loads(m["marks"]) if m["marks"] else [],
            "wordMarksSource": m["source"] or "none",
        })
    return rows


def index_by_key(rows: List[dict]) -> Dict[Tuple[str, str, str], dict]:
    """(combination, cadence, vocabulary) -> row."""
    out: Dict[Tuple[str, str, str], dict] = {}
    for r in rows:
        out[(r["combination"], r["cadence"], r["vocabulary"])] = r
    return out


def render_ts(entries: List[dict]) -> str:
    header = (
        "/**\n"
        " * Per-phrase timing manifest (A16 / issue #269).\n"
        " *\n"
        " * DO NOT EDIT — generated by `F:/voice-tools/venv/Scripts/python.exe\n"
        " * tools/voice/build_phrase_timing.py`.\n"
        " *\n"
        " * One entry per (combination, cadence). Consumed by RhythmSpine.beatsFor\n"
        " * and PunchAvatarCard so numbers and techniques audio, ring lighting and\n"
        " * the avatar's two-frame flip all resolve from one source of truth.\n"
        " *\n"
        " * A vocab entry without wordMarks reads `wordMarksSource: 'none'` and its\n"
        " * per-token onset/end are absent — the spine falls back to the beat grid\n"
        " * for that vocab. Fill those gaps by re-rendering; the QA loop lists them.\n"
        " */\n\n"
    )
    header += "export type PhraseTimingWordMarksSource =\n"
    header += "  | 'envelope'\n  | 'envelope-relaxed'\n  | 'whisper'\n  | 'none'\n\n"
    header += (
        "export interface PhraseTimingWord {\n"
        "  tokenIndex: number\n"
        "  token: string\n"
        "  onsetMs: number\n"
        "  endMs: number\n"
        "}\n\n"
        "export interface PhraseTimingVocab {\n"
        "  cueId: string\n"
        "  durationMs: number\n"
        "  wordMarksSource: PhraseTimingWordMarksSource\n"
        "  /** Per-token onsets + ends; empty when wordMarksSource === 'none'. */\n"
        "  words: PhraseTimingWord[]\n"
        "}\n\n"
        "export interface PhraseTimingEntry {\n"
        "  combination: string\n"
        "  cadence: string\n"
        "  tokens: readonly string[]\n"
        "  numbers?: PhraseTimingVocab\n"
        "  techniques?: PhraseTimingVocab\n"
        "  /**\n"
        "   * Per-token measured offset (`techniques.endMs[i] - numbers.endMs[i]`)\n"
        "   * in ms. Only present when BOTH vocabularies have wordMarks. The\n"
        "   * spine uses this to derive one vocab's timing from the other's\n"
        "   * without guessing.\n"
        "   */\n"
        "  vocabOffsetMs?: number[]\n"
        "}\n\n"
    )

    entries_ts = ",\n".join(json.dumps(e, indent=2, ensure_ascii=False) for e in entries)
    body = (
        f"export const PHRASE_TIMING: readonly PhraseTimingEntry[] = [\n"
        f"{entries_ts}\n"
        "] as const\n\n"
        "const INDEX = new Map<string, PhraseTimingEntry>()\n"
        "for (const entry of PHRASE_TIMING) {\n"
        "  INDEX.set(`${entry.combination}.${entry.cadence}`, entry)\n"
        "}\n\n"
        "export function findPhraseTiming(\n"
        "  combination: string,\n"
        "  cadence: string,\n"
        "): PhraseTimingEntry | undefined {\n"
        "  return INDEX.get(`${combination}.${cadence}`)\n"
        "}\n"
    )
    return header + body


def build(repo_root: str) -> Tuple[List[dict], List[dict]]:
    phrase_ts = os.path.join(repo_root, "src", "audio", "voiceAssets", "phraseManifest.ts")
    rows = load_phrases(phrase_ts)
    idx = index_by_key(rows)

    keys = sorted({(r["combination"], r["cadence"]) for r in rows})
    entries: List[dict] = []
    gaps: List[dict] = []
    for combo, cadence in keys:
        numbers = idx.get((combo, cadence, "numbers"))
        techniques = idx.get((combo, cadence, "techniques"))
        # Prefer numbers for the token list (both are the same when both exist).
        tokens = (numbers or techniques or {"tokens": []})["tokens"]
        entry: Dict[str, object] = {
            "combination": combo,
            "cadence": cadence,
            "tokens": tokens,
        }
        vocab_missing_marks: List[str] = []
        for vocab, row in (("numbers", numbers), ("techniques", techniques)):
            if row is None:
                vocab_missing_marks.append(f"missing-render:{vocab}")
                continue
            words = [
                {
                    "tokenIndex": m["tokenIndex"],
                    "token": m["token"],
                    "onsetMs": m["offsetMs"],
                    "endMs": m.get("endOffsetMs", m["offsetMs"]),
                }
                for m in row["wordMarks"]
                if "offsetMs" in m
            ]
            if row["wordMarksSource"] == "none" or not words:
                vocab_missing_marks.append(f"no-marks:{vocab}")
            entry[vocab] = {
                "cueId": row["cueId"],
                "durationMs": row["durationMs"],
                "wordMarksSource": row["wordMarksSource"],
                "words": words,
            }

        n = entry.get("numbers")
        t = entry.get("techniques")
        if n and t and n["words"] and t["words"] and len(n["words"]) == len(t["words"]):
            offsets = [
                t["words"][i]["endMs"] - n["words"][i]["endMs"]
                for i in range(len(n["words"]))
            ]
            entry["vocabOffsetMs"] = offsets
        entries.append(entry)
        if vocab_missing_marks:
            gaps.append({
                "combination": combo,
                "cadence": cadence,
                "issues": vocab_missing_marks,
            })
    return entries, gaps


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=None)
    args = ap.parse_args()
    repo_root = args.repo_root or os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..")
    )

    entries, gaps = build(repo_root)
    # Timing metadata is a domain artifact — the audio backend CONSUMES
    # it, not the other way round. Living under src/domain keeps the
    # purity-guard test happy and lets the spine import directly.
    ts_out = os.path.join(repo_root, "src", "domain", "programs", "phraseTimingManifest.ts")
    reports = os.path.join(repo_root, "tools", "analysis", "reports")
    os.makedirs(reports, exist_ok=True)

    open(ts_out, "w", encoding="utf-8").write(render_ts(entries))
    print(f"wrote {ts_out}: {len(entries)} entries")

    report_path = os.path.join(reports, "phrase-timing-audit.json")
    with open(report_path, "w", encoding="utf-8") as fh:
        json.dump({
            "entries": len(entries),
            "with_vocab_offset": sum(1 for e in entries if "vocabOffsetMs" in e),
            "gaps": gaps,
        }, fh, indent=2)
    print(f"wrote {report_path}: {len(gaps)} phrase(s) with gap(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
