/**
 * Persona audition assets (generated).
 *
 * DO NOT EDIT — produced by `node tools/voice/make-audition.mjs`.
 * These are a listening test, not production assets.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export interface AuditionAsset {
  cueId: string
  combination: string
  variant: string
  axis: string
  vocabulary: string
  performance: string
  spokenText: string
  durationMs: number
  profile: string
  module: number
}

export const auditionAssets: readonly AuditionAsset[] = [
  {
    cueId: "2b.numbers.work.land",
    combination: "2b",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two bee!",
    durationMs: 465,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.work.land.wav'),
  },
  {
    cueId: "2b.numbers.work.slam",
    combination: "2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two bee!",
    durationMs: 465,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.work.slam.wav'),
  },
  {
    cueId: "2b.numbers.work.shout",
    combination: "2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two bee!",
    durationMs: 465,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.work.shout.wav'),
  },
  {
    cueId: "2b.numbers.work.snap",
    combination: "2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two bee!",
    durationMs: 465,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.work.snap.wav'),
  },
  {
    cueId: "2b.numbers.push.land",
    combination: "2b",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two bee!",
    durationMs: 409,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.push.land.wav'),
  },
  {
    cueId: "2b.numbers.push.slam",
    combination: "2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two bee!",
    durationMs: 409,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.push.slam.wav'),
  },
  {
    cueId: "2b.numbers.push.shout",
    combination: "2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two bee!",
    durationMs: 409,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.push.shout.wav'),
  },
  {
    cueId: "2b.numbers.push.snap",
    combination: "2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two bee!",
    durationMs: 409,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.numbers.push.snap.wav'),
  },
  {
    cueId: "2b.techniques.work.land",
    combination: "2b",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body cross!",
    durationMs: 576,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.work.land.wav'),
  },
  {
    cueId: "2b.techniques.work.slam",
    combination: "2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body cross!",
    durationMs: 576,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.work.slam.wav'),
  },
  {
    cueId: "2b.techniques.work.shout",
    combination: "2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body cross!",
    durationMs: 576,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.work.shout.wav'),
  },
  {
    cueId: "2b.techniques.work.snap",
    combination: "2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body cross!",
    durationMs: 576,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.work.snap.wav'),
  },
  {
    cueId: "2b.techniques.push.land",
    combination: "2b",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body cross!",
    durationMs: 507,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.push.land.wav'),
  },
  {
    cueId: "2b.techniques.push.slam",
    combination: "2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body cross!",
    durationMs: 507,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.push.slam.wav'),
  },
  {
    cueId: "2b.techniques.push.shout",
    combination: "2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body cross!",
    durationMs: 507,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.push.shout.wav'),
  },
  {
    cueId: "2b.techniques.push.snap",
    combination: "2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body cross!",
    durationMs: 507,
    profile: "single",
    module: require('../../../assets/voice/audition/2b.techniques.push.snap.wav'),
  },
  {
    cueId: "1b.numbers.work.land",
    combination: "1b",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One bee!",
    durationMs: 425,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.work.land.wav'),
  },
  {
    cueId: "1b.numbers.work.slam",
    combination: "1b",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One bee!",
    durationMs: 425,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.work.slam.wav'),
  },
  {
    cueId: "1b.numbers.work.shout",
    combination: "1b",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One bee!",
    durationMs: 425,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.work.shout.wav'),
  },
  {
    cueId: "1b.numbers.work.snap",
    combination: "1b",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One bee!",
    durationMs: 425,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.work.snap.wav'),
  },
  {
    cueId: "1b.numbers.push.land",
    combination: "1b",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One bee!",
    durationMs: 398,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.push.land.wav'),
  },
  {
    cueId: "1b.numbers.push.slam",
    combination: "1b",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One bee!",
    durationMs: 398,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.push.slam.wav'),
  },
  {
    cueId: "1b.numbers.push.shout",
    combination: "1b",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One bee!",
    durationMs: 398,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.push.shout.wav'),
  },
  {
    cueId: "1b.numbers.push.snap",
    combination: "1b",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One bee!",
    durationMs: 398,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.numbers.push.snap.wav'),
  },
  {
    cueId: "1b.techniques.work.land",
    combination: "1b",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body jab!",
    durationMs: 546,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.work.land.wav'),
  },
  {
    cueId: "1b.techniques.work.slam",
    combination: "1b",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body jab!",
    durationMs: 546,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.work.slam.wav'),
  },
  {
    cueId: "1b.techniques.work.shout",
    combination: "1b",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body jab!",
    durationMs: 546,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.work.shout.wav'),
  },
  {
    cueId: "1b.techniques.work.snap",
    combination: "1b",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Body jab!",
    durationMs: 546,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.work.snap.wav'),
  },
  {
    cueId: "1b.techniques.push.land",
    combination: "1b",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body jab!",
    durationMs: 487,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.push.land.wav'),
  },
  {
    cueId: "1b.techniques.push.slam",
    combination: "1b",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body jab!",
    durationMs: 487,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.push.slam.wav'),
  },
  {
    cueId: "1b.techniques.push.shout",
    combination: "1b",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body jab!",
    durationMs: 487,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.push.shout.wav'),
  },
  {
    cueId: "1b.techniques.push.snap",
    combination: "1b",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Body jab!",
    durationMs: 487,
    profile: "single",
    module: require('../../../assets/voice/audition/1b.techniques.push.snap.wav'),
  },
  {
    cueId: "1-2b.numbers.work.land",
    combination: "1-2b",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee!",
    durationMs: 884,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.work.land.wav'),
  },
  {
    cueId: "1-2b.numbers.work.slam",
    combination: "1-2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee!",
    durationMs: 884,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.work.slam.wav'),
  },
  {
    cueId: "1-2b.numbers.work.shout",
    combination: "1-2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee!",
    durationMs: 884,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.work.shout.wav'),
  },
  {
    cueId: "1-2b.numbers.work.snap",
    combination: "1-2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee!",
    durationMs: 884,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.work.snap.wav'),
  },
  {
    cueId: "1-2b.numbers.push.land",
    combination: "1-2b",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee!",
    durationMs: 814,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.push.land.wav'),
  },
  {
    cueId: "1-2b.numbers.push.slam",
    combination: "1-2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee!",
    durationMs: 814,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.push.slam.wav'),
  },
  {
    cueId: "1-2b.numbers.push.shout",
    combination: "1-2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee!",
    durationMs: 814,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.push.shout.wav'),
  },
  {
    cueId: "1-2b.numbers.push.snap",
    combination: "1-2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee!",
    durationMs: 814,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.numbers.push.snap.wav'),
  },
  {
    cueId: "1-2b.techniques.work.land",
    combination: "1-2b",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross!",
    durationMs: 1127,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.work.land.wav'),
  },
  {
    cueId: "1-2b.techniques.work.slam",
    combination: "1-2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross!",
    durationMs: 1127,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.work.slam.wav'),
  },
  {
    cueId: "1-2b.techniques.work.shout",
    combination: "1-2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross!",
    durationMs: 1127,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.work.shout.wav'),
  },
  {
    cueId: "1-2b.techniques.work.snap",
    combination: "1-2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross!",
    durationMs: 1127,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.work.snap.wav'),
  },
  {
    cueId: "1-2b.techniques.push.land",
    combination: "1-2b",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross!",
    durationMs: 1088,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.push.land.wav'),
  },
  {
    cueId: "1-2b.techniques.push.slam",
    combination: "1-2b",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross!",
    durationMs: 1088,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.push.slam.wav'),
  },
  {
    cueId: "1-2b.techniques.push.shout",
    combination: "1-2b",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross!",
    durationMs: 1088,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.push.shout.wav'),
  },
  {
    cueId: "1-2b.techniques.push.snap",
    combination: "1-2b",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross!",
    durationMs: 1088,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b.techniques.push.snap.wav'),
  },
  {
    cueId: "2-3-2.numbers.work.land",
    combination: "2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two!",
    durationMs: 976,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.work.land.wav'),
  },
  {
    cueId: "2-3-2.numbers.work.slam",
    combination: "2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two!",
    durationMs: 976,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.work.slam.wav'),
  },
  {
    cueId: "2-3-2.numbers.work.shout",
    combination: "2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two!",
    durationMs: 976,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.work.shout.wav'),
  },
  {
    cueId: "2-3-2.numbers.work.snap",
    combination: "2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two!",
    durationMs: 976,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.work.snap.wav'),
  },
  {
    cueId: "2-3-2.numbers.push.land",
    combination: "2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two!",
    durationMs: 871,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.push.land.wav'),
  },
  {
    cueId: "2-3-2.numbers.push.slam",
    combination: "2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two!",
    durationMs: 871,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.push.slam.wav'),
  },
  {
    cueId: "2-3-2.numbers.push.shout",
    combination: "2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two!",
    durationMs: 871,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.push.shout.wav'),
  },
  {
    cueId: "2-3-2.numbers.push.snap",
    combination: "2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two!",
    durationMs: 871,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.numbers.push.snap.wav'),
  },
  {
    cueId: "2-3-2.techniques.work.land",
    combination: "2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1198,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.work.land.wav'),
  },
  {
    cueId: "2-3-2.techniques.work.slam",
    combination: "2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1198,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.work.slam.wav'),
  },
  {
    cueId: "2-3-2.techniques.work.shout",
    combination: "2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1198,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.work.shout.wav'),
  },
  {
    cueId: "2-3-2.techniques.work.snap",
    combination: "2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1198,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.work.snap.wav'),
  },
  {
    cueId: "2-3-2.techniques.push.land",
    combination: "2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1103,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.push.land.wav'),
  },
  {
    cueId: "2-3-2.techniques.push.slam",
    combination: "2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1103,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.push.slam.wav'),
  },
  {
    cueId: "2-3-2.techniques.push.shout",
    combination: "2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1103,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.push.shout.wav'),
  },
  {
    cueId: "2-3-2.techniques.push.snap",
    combination: "2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross!",
    durationMs: 1103,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2.techniques.push.snap.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.land",
    combination: "1-2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1106,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.land.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.slam",
    combination: "1-2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1106,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.slam.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.shout",
    combination: "1-2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1106,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.shout.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.snap",
    combination: "1-2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1106,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.snap.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.land",
    combination: "1-2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.land.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.slam",
    combination: "1-2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.slam.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.shout",
    combination: "1-2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.shout.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.snap",
    combination: "1-2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.snap.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.land",
    combination: "1-2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.land.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.slam",
    combination: "1-2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.slam.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.shout",
    combination: "1-2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.shout.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.snap",
    combination: "1-2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.snap.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.land",
    combination: "1-2-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.land.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.slam",
    combination: "1-2-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.slam.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.shout",
    combination: "1-2-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.shout.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.snap",
    combination: "1-2-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.snap.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.work.land",
    combination: "1-2b-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee, three two!",
    durationMs: 1289,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.work.land.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.work.slam",
    combination: "1-2b-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee, three two!",
    durationMs: 1289,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.work.slam.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.work.shout",
    combination: "1-2b-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee, three two!",
    durationMs: 1289,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.work.shout.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.work.snap",
    combination: "1-2b-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two bee, three two!",
    durationMs: 1289,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.work.snap.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.push.land",
    combination: "1-2b-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee, three two!",
    durationMs: 1202,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.push.land.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.push.slam",
    combination: "1-2b-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee, three two!",
    durationMs: 1202,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.push.slam.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.push.shout",
    combination: "1-2b-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee, three two!",
    durationMs: 1202,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.push.shout.wav'),
  },
  {
    cueId: "1-2b-3-2.numbers.push.snap",
    combination: "1-2b-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two bee, three two!",
    durationMs: 1202,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.numbers.push.snap.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.work.land",
    combination: "1-2b-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1857,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.work.land.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.work.slam",
    combination: "1-2b-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1857,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.work.slam.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.work.shout",
    combination: "1-2b-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1857,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.work.shout.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.work.snap",
    combination: "1-2b-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1857,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.work.snap.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.push.land",
    combination: "1-2b-3-2",
    variant: "land",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1664,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.push.land.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.push.slam",
    combination: "1-2b-3-2",
    variant: "slam",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1664,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.push.slam.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.push.shout",
    combination: "1-2b-3-2",
    variant: "shout",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1664,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.push.shout.wav'),
  },
  {
    cueId: "1-2b-3-2.techniques.push.snap",
    combination: "1-2b-3-2",
    variant: "snap",
    axis: "finish",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab body cross, lead hook cross!",
    durationMs: 1664,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2b-3-2.techniques.push.snap.wav'),
  },
]

/* eslint-enable @typescript-eslint/no-require-imports */
