/**
 * Persona audition assets (generated).
 *
 * DO NOT EDIT — produced by `node tools/voice/make-audition.mjs`.
 * These are a listening test, not production assets.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export interface AuditionAsset {
  cueId: string
  combination: string
  variant: string
  axis: string
  vocabulary: string
  performance: string
  spokenText: string
  durationMs: number
  profile: string
  module: number
}

export const auditionAssets: readonly AuditionAsset[] = [
  {
    cueId: "1.numbers.work.current",
    combination: "1",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One!",
    durationMs: 347,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.work.current.wav'),
  },
  {
    cueId: "1.numbers.work.chest",
    combination: "1",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One!",
    durationMs: 352,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.work.chest.wav'),
  },
  {
    cueId: "1.numbers.work.grit",
    combination: "1",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One!",
    durationMs: 349,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.work.grit.wav'),
  },
  {
    cueId: "1.numbers.work.close",
    combination: "1",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One!",
    durationMs: 340,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.work.close.wav'),
  },
  {
    cueId: "1.numbers.work.broadcast",
    combination: "1",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One!",
    durationMs: 347,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.work.broadcast.wav'),
  },
  {
    cueId: "1.numbers.push.current",
    combination: "1",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One!",
    durationMs: 325,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.push.current.wav'),
  },
  {
    cueId: "1.numbers.push.chest",
    combination: "1",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One!",
    durationMs: 332,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.push.chest.wav'),
  },
  {
    cueId: "1.numbers.push.grit",
    combination: "1",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One!",
    durationMs: 331,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.push.grit.wav'),
  },
  {
    cueId: "1.numbers.push.close",
    combination: "1",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One!",
    durationMs: 321,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.push.close.wav'),
  },
  {
    cueId: "1.numbers.push.broadcast",
    combination: "1",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One!",
    durationMs: 325,
    profile: "single",
    module: require('../../../assets/voice/audition/1.numbers.push.broadcast.wav'),
  },
  {
    cueId: "1.techniques.work.current",
    combination: "1",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab!",
    durationMs: 424,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.work.current.wav'),
  },
  {
    cueId: "1.techniques.work.chest",
    combination: "1",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab!",
    durationMs: 437,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.work.chest.wav'),
  },
  {
    cueId: "1.techniques.work.grit",
    combination: "1",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab!",
    durationMs: 432,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.work.grit.wav'),
  },
  {
    cueId: "1.techniques.work.close",
    combination: "1",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab!",
    durationMs: 416,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.work.close.wav'),
  },
  {
    cueId: "1.techniques.work.broadcast",
    combination: "1",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab!",
    durationMs: 424,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.work.broadcast.wav'),
  },
  {
    cueId: "1.techniques.push.current",
    combination: "1",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab!",
    durationMs: 377,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.push.current.wav'),
  },
  {
    cueId: "1.techniques.push.chest",
    combination: "1",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab!",
    durationMs: 378,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.push.chest.wav'),
  },
  {
    cueId: "1.techniques.push.grit",
    combination: "1",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab!",
    durationMs: 383,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.push.grit.wav'),
  },
  {
    cueId: "1.techniques.push.close",
    combination: "1",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab!",
    durationMs: 374,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.push.close.wav'),
  },
  {
    cueId: "1.techniques.push.broadcast",
    combination: "1",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab!",
    durationMs: 377,
    profile: "single",
    module: require('../../../assets/voice/audition/1.techniques.push.broadcast.wav'),
  },
  {
    cueId: "1-2.numbers.work.current",
    combination: "1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two!",
    durationMs: 724,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.work.current.wav'),
  },
  {
    cueId: "1-2.numbers.work.chest",
    combination: "1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two!",
    durationMs: 739,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.work.chest.wav'),
  },
  {
    cueId: "1-2.numbers.work.grit",
    combination: "1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two!",
    durationMs: 733,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.work.grit.wav'),
  },
  {
    cueId: "1-2.numbers.work.close",
    combination: "1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two!",
    durationMs: 706,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.work.close.wav'),
  },
  {
    cueId: "1-2.numbers.work.broadcast",
    combination: "1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two!",
    durationMs: 724,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.work.broadcast.wav'),
  },
  {
    cueId: "1-2.numbers.push.current",
    combination: "1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two!",
    durationMs: 679,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.push.current.wav'),
  },
  {
    cueId: "1-2.numbers.push.chest",
    combination: "1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two!",
    durationMs: 684,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.push.chest.wav'),
  },
  {
    cueId: "1-2.numbers.push.grit",
    combination: "1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two!",
    durationMs: 694,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.push.grit.wav'),
  },
  {
    cueId: "1-2.numbers.push.close",
    combination: "1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two!",
    durationMs: 661,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.push.close.wav'),
  },
  {
    cueId: "1-2.numbers.push.broadcast",
    combination: "1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two!",
    durationMs: 679,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.numbers.push.broadcast.wav'),
  },
  {
    cueId: "1-2.techniques.work.current",
    combination: "1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross!",
    durationMs: 840,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.work.current.wav'),
  },
  {
    cueId: "1-2.techniques.work.chest",
    combination: "1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross!",
    durationMs: 858,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.work.chest.wav'),
  },
  {
    cueId: "1-2.techniques.work.grit",
    combination: "1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross!",
    durationMs: 851,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.work.grit.wav'),
  },
  {
    cueId: "1-2.techniques.work.close",
    combination: "1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross!",
    durationMs: 816,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.work.close.wav'),
  },
  {
    cueId: "1-2.techniques.work.broadcast",
    combination: "1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross!",
    durationMs: 840,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.work.broadcast.wav'),
  },
  {
    cueId: "1-2.techniques.push.current",
    combination: "1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross!",
    durationMs: 786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.push.current.wav'),
  },
  {
    cueId: "1-2.techniques.push.chest",
    combination: "1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross!",
    durationMs: 783,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.push.chest.wav'),
  },
  {
    cueId: "1-2.techniques.push.grit",
    combination: "1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross!",
    durationMs: 790,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.push.grit.wav'),
  },
  {
    cueId: "1-2.techniques.push.close",
    combination: "1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross!",
    durationMs: 770,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.push.close.wav'),
  },
  {
    cueId: "1-2.techniques.push.broadcast",
    combination: "1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross!",
    durationMs: 786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.techniques.push.broadcast.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.current",
    combination: "1-2-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1106,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.current.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.chest",
    combination: "1-2-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1113,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.chest.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.grit",
    combination: "1-2-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1115,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.grit.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.close",
    combination: "1-2-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1085,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.close.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.work.broadcast",
    combination: "1-2-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two, three two!",
    durationMs: 1106,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.work.broadcast.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.current",
    combination: "1-2-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.current.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.chest",
    combination: "1-2-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1058,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.chest.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.grit",
    combination: "1-2-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1060,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.grit.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.close",
    combination: "1-2-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1036,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.close.wav'),
  },
  {
    cueId: "1-2-3-2.numbers.push.broadcast",
    combination: "1-2-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.numbers.push.broadcast.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.current",
    combination: "1-2-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.current.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.chest",
    combination: "1-2-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1534,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.chest.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.grit",
    combination: "1-2-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1528,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.grit.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.close",
    combination: "1-2-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1503,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.close.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.work.broadcast",
    combination: "1-2-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.work.broadcast.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.current",
    combination: "1-2-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.current.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.chest",
    combination: "1-2-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1396,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.chest.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.grit",
    combination: "1-2-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1401,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.grit.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.close",
    combination: "1-2-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1362,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.close.wav'),
  },
  {
    cueId: "1-2-3-2.techniques.push.broadcast",
    combination: "1-2-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.techniques.push.broadcast.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.work.current",
    combination: "1-2-roll-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2042,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.work.current.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.work.chest",
    combination: "1-2-roll-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2054,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.work.chest.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.work.grit",
    combination: "1-2-roll-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2048,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.work.grit.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.work.close",
    combination: "1-2-roll-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2022,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.work.close.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.work.broadcast",
    combination: "1-2-roll-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2042,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.work.broadcast.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.push.current",
    combination: "1-2-roll-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1772,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.push.current.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.push.chest",
    combination: "1-2-roll-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1778,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.push.chest.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.push.grit",
    combination: "1-2-roll-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1781,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.push.grit.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.push.close",
    combination: "1-2-roll-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1747,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.push.close.wav'),
  },
  {
    cueId: "1-2-roll-3-2.numbers.push.broadcast",
    combination: "1-2-roll-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1772,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.numbers.push.broadcast.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.work.current",
    combination: "1-2-roll-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2405,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.work.current.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.work.chest",
    combination: "1-2-roll-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2414,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.work.chest.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.work.grit",
    combination: "1-2-roll-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2416,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.work.grit.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.work.close",
    combination: "1-2-roll-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2391,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.work.close.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.work.broadcast",
    combination: "1-2-roll-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2405,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.work.broadcast.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.push.current",
    combination: "1-2-roll-3-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2155,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.push.current.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.push.chest",
    combination: "1-2-roll-3-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2170,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.push.chest.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.push.grit",
    combination: "1-2-roll-3-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2165,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.push.grit.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.push.close",
    combination: "1-2-roll-3-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2136,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.push.close.wav'),
  },
  {
    cueId: "1-2-roll-3-2.techniques.push.broadcast",
    combination: "1-2-roll-3-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2155,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.techniques.push.broadcast.wav'),
  },
  {
    cueId: "1-slip-2.numbers.work.current",
    combination: "1-slip-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One... Slip!... Two!",
    durationMs: 1566,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.work.current.wav'),
  },
  {
    cueId: "1-slip-2.numbers.work.chest",
    combination: "1-slip-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One... Slip!... Two!",
    durationMs: 1577,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.work.chest.wav'),
  },
  {
    cueId: "1-slip-2.numbers.work.grit",
    combination: "1-slip-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One... Slip!... Two!",
    durationMs: 1578,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.work.grit.wav'),
  },
  {
    cueId: "1-slip-2.numbers.work.close",
    combination: "1-slip-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One... Slip!... Two!",
    durationMs: 1545,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.work.close.wav'),
  },
  {
    cueId: "1-slip-2.numbers.work.broadcast",
    combination: "1-slip-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "One... Slip!... Two!",
    durationMs: 1566,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.work.broadcast.wav'),
  },
  {
    cueId: "1-slip-2.numbers.push.current",
    combination: "1-slip-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One... Slip!... Two!",
    durationMs: 1308,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.push.current.wav'),
  },
  {
    cueId: "1-slip-2.numbers.push.chest",
    combination: "1-slip-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One... Slip!... Two!",
    durationMs: 1311,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.push.chest.wav'),
  },
  {
    cueId: "1-slip-2.numbers.push.grit",
    combination: "1-slip-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One... Slip!... Two!",
    durationMs: 1312,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.push.grit.wav'),
  },
  {
    cueId: "1-slip-2.numbers.push.close",
    combination: "1-slip-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One... Slip!... Two!",
    durationMs: 1288,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.push.close.wav'),
  },
  {
    cueId: "1-slip-2.numbers.push.broadcast",
    combination: "1-slip-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "One... Slip!... Two!",
    durationMs: 1308,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.numbers.push.broadcast.wav'),
  },
  {
    cueId: "1-slip-2.techniques.work.current",
    combination: "1-slip-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1719,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.work.current.wav'),
  },
  {
    cueId: "1-slip-2.techniques.work.chest",
    combination: "1-slip-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1733,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.work.chest.wav'),
  },
  {
    cueId: "1-slip-2.techniques.work.grit",
    combination: "1-slip-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1733,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.work.grit.wav'),
  },
  {
    cueId: "1-slip-2.techniques.work.close",
    combination: "1-slip-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1702,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.work.close.wav'),
  },
  {
    cueId: "1-slip-2.techniques.work.broadcast",
    combination: "1-slip-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1719,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.work.broadcast.wav'),
  },
  {
    cueId: "1-slip-2.techniques.push.current",
    combination: "1-slip-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1541,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.push.current.wav'),
  },
  {
    cueId: "1-slip-2.techniques.push.chest",
    combination: "1-slip-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1550,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.push.chest.wav'),
  },
  {
    cueId: "1-slip-2.techniques.push.grit",
    combination: "1-slip-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1546,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.push.grit.wav'),
  },
  {
    cueId: "1-slip-2.techniques.push.close",
    combination: "1-slip-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1523,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.push.close.wav'),
  },
  {
    cueId: "1-slip-2.techniques.push.broadcast",
    combination: "1-slip-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1541,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.techniques.push.broadcast.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.work.current",
    combination: "2-3-2-roll-1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2231,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.work.current.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.work.chest",
    combination: "2-3-2-roll-1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2232,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.work.chest.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.work.grit",
    combination: "2-3-2-roll-1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2232,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.work.grit.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.work.close",
    combination: "2-3-2-roll-1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2207,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.work.close.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.work.broadcast",
    combination: "2-3-2-roll-1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "work",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2231,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.work.broadcast.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.push.current",
    combination: "2-3-2-roll-1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1945,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.push.current.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.push.chest",
    combination: "2-3-2-roll-1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1960,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.push.chest.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.push.grit",
    combination: "2-3-2-roll-1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1958,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.push.grit.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.push.close",
    combination: "2-3-2-roll-1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1929,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.push.close.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.numbers.push.broadcast",
    combination: "2-3-2-roll-1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "numbers",
    performance: "push",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1945,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.numbers.push.broadcast.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.work.current",
    combination: "2-3-2-roll-1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2759,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.work.current.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.work.chest",
    combination: "2-3-2-roll-1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2775,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.work.chest.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.work.grit",
    combination: "2-3-2-roll-1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2773,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.work.grit.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.work.close",
    combination: "2-3-2-roll-1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2743,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.work.close.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.work.broadcast",
    combination: "2-3-2-roll-1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "work",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2759,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.work.broadcast.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.push.current",
    combination: "2-3-2-roll-1-2",
    variant: "current",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2410,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.push.current.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.push.chest",
    combination: "2-3-2-roll-1-2",
    variant: "chest",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2423,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.push.chest.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.push.grit",
    combination: "2-3-2-roll-1-2",
    variant: "grit",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2421,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.push.grit.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.push.close",
    combination: "2-3-2-roll-1-2",
    variant: "close",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2394,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.push.close.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.techniques.push.broadcast",
    combination: "2-3-2-roll-1-2",
    variant: "broadcast",
    axis: "texture",
    vocabulary: "techniques",
    performance: "push",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2410,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.techniques.push.broadcast.wav'),
  },
]

/* eslint-enable @typescript-eslint/no-require-imports */
