/**
 * Persona audition assets (generated).
 *
 * DO NOT EDIT — produced by `node tools/voice/make-audition.mjs`.
 * These are a listening test, not production assets.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export interface AuditionAsset {
  cueId: string
  combination: string
  blend: string
  vocabulary: string
  performance: string
  expression: string
  spokenText: string
  durationMs: number
  profile: string
  module: number
}

export const auditionAssets: readonly AuditionAsset[] = [
  {
    cueId: "1.aged-melodic.numbers.teach.measured",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "measured",
    spokenText: "One.",
    durationMs: 397,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.teach.measured.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.teach.expressive",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "expressive",
    spokenText: "One.",
    durationMs: 401,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.teach.expressive.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.teach.theatrical",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "theatrical",
    spokenText: "One.",
    durationMs: 398,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.teach.theatrical.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.work.measured",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "measured",
    spokenText: "One!",
    durationMs: 351,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.work.measured.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.work.expressive",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "expressive",
    spokenText: "One!",
    durationMs: 344,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.work.expressive.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.work.theatrical",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "theatrical",
    spokenText: "One!",
    durationMs: 350,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.work.theatrical.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.push.measured",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "measured",
    spokenText: "One!",
    durationMs: 326,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.push.measured.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.push.expressive",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "expressive",
    spokenText: "One!",
    durationMs: 325,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.push.expressive.wav'),
  },
  {
    cueId: "1.aged-melodic.numbers.push.theatrical",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "theatrical",
    spokenText: "One!",
    durationMs: 325,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.numbers.push.theatrical.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.teach.measured",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "measured",
    spokenText: "Jab.",
    durationMs: 476,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.teach.measured.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.teach.expressive",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "expressive",
    spokenText: "Jab.",
    durationMs: 481,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.teach.expressive.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.teach.theatrical",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "theatrical",
    spokenText: "Jab.",
    durationMs: 477,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.teach.theatrical.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.work.measured",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "measured",
    spokenText: "Jab!",
    durationMs: 429,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.work.measured.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.work.expressive",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "expressive",
    spokenText: "Jab!",
    durationMs: 424,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.work.expressive.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.work.theatrical",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "theatrical",
    spokenText: "Jab!",
    durationMs: 429,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.work.theatrical.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.push.measured",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "measured",
    spokenText: "Jab!",
    durationMs: 377,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.push.measured.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.push.expressive",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "expressive",
    spokenText: "Jab!",
    durationMs: 371,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.push.expressive.wav'),
  },
  {
    cueId: "1.aged-melodic.techniques.push.theatrical",
    combination: "1",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "theatrical",
    spokenText: "Jab!",
    durationMs: 374,
    profile: "single",
    module: require('../../../assets/voice/audition/1.aged-melodic.techniques.push.theatrical.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.teach.measured",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "measured",
    spokenText: "One two.",
    durationMs: 808,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.teach.measured.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.teach.expressive",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "expressive",
    spokenText: "One two.",
    durationMs: 808,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.teach.expressive.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.teach.theatrical",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "theatrical",
    spokenText: "One two.",
    durationMs: 808,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.teach.theatrical.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.work.measured",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "measured",
    spokenText: "One two!",
    durationMs: 724,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.work.measured.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.work.expressive",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "expressive",
    spokenText: "One two!",
    durationMs: 724,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.work.expressive.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.work.theatrical",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "theatrical",
    spokenText: "One two!",
    durationMs: 724,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.work.theatrical.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.push.measured",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "measured",
    spokenText: "One two!",
    durationMs: 678,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.push.measured.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.push.expressive",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "expressive",
    spokenText: "One two!",
    durationMs: 678,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.push.expressive.wav'),
  },
  {
    cueId: "1-2.aged-melodic.numbers.push.theatrical",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "theatrical",
    spokenText: "One two!",
    durationMs: 679,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.numbers.push.theatrical.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.teach.measured",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "measured",
    spokenText: "Jab cross.",
    durationMs: 911,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.teach.measured.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.teach.expressive",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "expressive",
    spokenText: "Jab cross.",
    durationMs: 910,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.teach.expressive.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.teach.theatrical",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "theatrical",
    spokenText: "Jab cross.",
    durationMs: 910,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.teach.theatrical.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.work.measured",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "measured",
    spokenText: "Jab cross!",
    durationMs: 840,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.work.measured.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.work.expressive",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "expressive",
    spokenText: "Jab cross!",
    durationMs: 840,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.work.expressive.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.work.theatrical",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "theatrical",
    spokenText: "Jab cross!",
    durationMs: 840,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.work.theatrical.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.push.measured",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "measured",
    spokenText: "Jab cross!",
    durationMs: 786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.push.measured.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.push.expressive",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "expressive",
    spokenText: "Jab cross!",
    durationMs: 786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.push.expressive.wav'),
  },
  {
    cueId: "1-2.aged-melodic.techniques.push.theatrical",
    combination: "1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "theatrical",
    spokenText: "Jab cross!",
    durationMs: 786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2.aged-melodic.techniques.push.theatrical.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.teach.measured",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "measured",
    spokenText: "One two... three two.",
    durationMs: 1400,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.teach.measured.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.teach.expressive",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "expressive",
    spokenText: "One two... three two.",
    durationMs: 1405,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.teach.expressive.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.teach.theatrical",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "theatrical",
    spokenText: "One two... three two.",
    durationMs: 1409,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.teach.theatrical.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.work.measured",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "measured",
    spokenText: "One two, three two!",
    durationMs: 1107,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.work.measured.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.work.expressive",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "expressive",
    spokenText: "One two, three two!",
    durationMs: 1105,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.work.expressive.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.work.theatrical",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "theatrical",
    spokenText: "One two, three two!",
    durationMs: 1106,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.work.theatrical.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.push.measured",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "measured",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.push.measured.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.push.expressive",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "expressive",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.push.expressive.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.numbers.push.theatrical",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "theatrical",
    spokenText: "One two, three two!",
    durationMs: 1053,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.numbers.push.theatrical.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.teach.measured",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "measured",
    spokenText: "Jab cross... lead hook cross.",
    durationMs: 1786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.teach.measured.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.teach.expressive",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "expressive",
    spokenText: "Jab cross... lead hook cross.",
    durationMs: 1786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.teach.expressive.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.teach.theatrical",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "theatrical",
    spokenText: "Jab cross... lead hook cross.",
    durationMs: 1786,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.teach.theatrical.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.work.measured",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "measured",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.work.measured.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.work.expressive",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "expressive",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.work.expressive.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.work.theatrical",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "theatrical",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1516,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.work.theatrical.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.push.measured",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "measured",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.push.measured.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.push.expressive",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "expressive",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.push.expressive.wav'),
  },
  {
    cueId: "1-2-3-2.aged-melodic.techniques.push.theatrical",
    combination: "1-2-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "theatrical",
    spokenText: "Jab cross, lead hook cross!",
    durationMs: 1387,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-3-2.aged-melodic.techniques.push.theatrical.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.teach.measured",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "measured",
    spokenText: "One two... Roll!... Three two.",
    durationMs: 2256,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.teach.measured.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.teach.expressive",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "expressive",
    spokenText: "One two... Roll!... Three two.",
    durationMs: 2259,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.teach.expressive.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.teach.theatrical",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "theatrical",
    spokenText: "One two... Roll!... Three two.",
    durationMs: 2258,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.teach.theatrical.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.work.measured",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "measured",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2042,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.work.measured.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.work.expressive",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "expressive",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2042,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.work.expressive.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.work.theatrical",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "theatrical",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 2042,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.work.theatrical.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.push.measured",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "measured",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1772,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.push.measured.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.push.expressive",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "expressive",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1772,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.push.expressive.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.numbers.push.theatrical",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "theatrical",
    spokenText: "One two... Roll!... Three two!",
    durationMs: 1772,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.numbers.push.theatrical.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.teach.measured",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "measured",
    spokenText: "Jab cross... Roll!... Lead hook cross.",
    durationMs: 2685,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.teach.measured.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.teach.expressive",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "expressive",
    spokenText: "Jab cross... Roll!... Lead hook cross.",
    durationMs: 2685,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.teach.expressive.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.teach.theatrical",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "theatrical",
    spokenText: "Jab cross... Roll!... Lead hook cross.",
    durationMs: 2685,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.teach.theatrical.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.work.measured",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "measured",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2405,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.work.measured.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.work.expressive",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "expressive",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2405,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.work.expressive.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.work.theatrical",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "theatrical",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2405,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.work.theatrical.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.push.measured",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "measured",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2155,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.push.measured.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.push.expressive",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "expressive",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2155,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.push.expressive.wav'),
  },
  {
    cueId: "1-2-roll-3-2.aged-melodic.techniques.push.theatrical",
    combination: "1-2-roll-3-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "theatrical",
    spokenText: "Jab cross... Roll!... Lead hook cross!",
    durationMs: 2155,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-2-roll-3-2.aged-melodic.techniques.push.theatrical.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.teach.measured",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "measured",
    spokenText: "One... Slip!... Two.",
    durationMs: 1832,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.teach.measured.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.teach.expressive",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "expressive",
    spokenText: "One... Slip!... Two.",
    durationMs: 1831,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.teach.expressive.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.teach.theatrical",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "theatrical",
    spokenText: "One... Slip!... Two.",
    durationMs: 1830,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.teach.theatrical.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.work.measured",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "measured",
    spokenText: "One... Slip!... Two!",
    durationMs: 1559,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.work.measured.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.work.expressive",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "expressive",
    spokenText: "One... Slip!... Two!",
    durationMs: 1563,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.work.expressive.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.work.theatrical",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "theatrical",
    spokenText: "One... Slip!... Two!",
    durationMs: 1566,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.work.theatrical.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.push.measured",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "measured",
    spokenText: "One... Slip!... Two!",
    durationMs: 1310,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.push.measured.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.push.expressive",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "expressive",
    spokenText: "One... Slip!... Two!",
    durationMs: 1234,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.push.expressive.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.numbers.push.theatrical",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "theatrical",
    spokenText: "One... Slip!... Two!",
    durationMs: 1308,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.numbers.push.theatrical.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.teach.measured",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "measured",
    spokenText: "Jab... Slip!... Cross.",
    durationMs: 1981,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.teach.measured.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.teach.expressive",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "expressive",
    spokenText: "Jab... Slip!... Cross.",
    durationMs: 1990,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.teach.expressive.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.teach.theatrical",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "theatrical",
    spokenText: "Jab... Slip!... Cross.",
    durationMs: 1989,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.teach.theatrical.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.work.measured",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "measured",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1719,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.work.measured.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.work.expressive",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "expressive",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1719,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.work.expressive.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.work.theatrical",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "theatrical",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1719,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.work.theatrical.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.push.measured",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "measured",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1541,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.push.measured.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.push.expressive",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "expressive",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1541,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.push.expressive.wav'),
  },
  {
    cueId: "1-slip-2.aged-melodic.techniques.push.theatrical",
    combination: "1-slip-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "theatrical",
    spokenText: "Jab... Slip!... Cross!",
    durationMs: 1541,
    profile: "combination",
    module: require('../../../assets/voice/audition/1-slip-2.aged-melodic.techniques.push.theatrical.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.teach.measured",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "measured",
    spokenText: "Two three... two... Roll!... One two.",
    durationMs: 2642,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.teach.measured.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.teach.expressive",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "expressive",
    spokenText: "Two three... two... Roll!... One two.",
    durationMs: 2642,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.teach.expressive.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.teach.theatrical",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "teach",
    expression: "theatrical",
    spokenText: "Two three... two... Roll!... One two.",
    durationMs: 2642,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.teach.theatrical.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.work.measured",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "measured",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2231,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.work.measured.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.work.expressive",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "expressive",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2231,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.work.expressive.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.work.theatrical",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "work",
    expression: "theatrical",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 2231,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.work.theatrical.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.push.measured",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "measured",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1945,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.push.measured.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.push.expressive",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "expressive",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1945,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.push.expressive.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.numbers.push.theatrical",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "numbers",
    performance: "push",
    expression: "theatrical",
    spokenText: "Two three, two... Roll!... One two!",
    durationMs: 1945,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.numbers.push.theatrical.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.teach.measured",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "measured",
    spokenText: "Cross lead hook... cross... Roll!... Jab cross.",
    durationMs: 3221,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.teach.measured.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.teach.expressive",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "expressive",
    spokenText: "Cross lead hook... cross... Roll!... Jab cross.",
    durationMs: 3221,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.teach.expressive.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.teach.theatrical",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "teach",
    expression: "theatrical",
    spokenText: "Cross lead hook... cross... Roll!... Jab cross.",
    durationMs: 3221,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.teach.theatrical.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.work.measured",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "measured",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2759,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.work.measured.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.work.expressive",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "expressive",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2759,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.work.expressive.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.work.theatrical",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "work",
    expression: "theatrical",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2759,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.work.theatrical.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.push.measured",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "measured",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2410,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.push.measured.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.push.expressive",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "expressive",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2410,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.push.expressive.wav'),
  },
  {
    cueId: "2-3-2-roll-1-2.aged-melodic.techniques.push.theatrical",
    combination: "2-3-2-roll-1-2",
    blend: "aged-melodic",
    vocabulary: "techniques",
    performance: "push",
    expression: "theatrical",
    spokenText: "Cross lead hook, cross... Roll!... Jab cross!",
    durationMs: 2410,
    profile: "combination",
    module: require('../../../assets/voice/audition/2-3-2-roll-1-2.aged-melodic.techniques.push.theatrical.wav'),
  },
]

/* eslint-enable @typescript-eslint/no-require-imports */
