/**
 * Whole-phrase combination assets (generated).
 *
 * DO NOT EDIT — produced by `node tools/voice/make-phrase-clips.mjs`.
 *
 * One clip per (combination, cadence), spoken by the settled Old-School
 * Cornerman persona. `wordMarks` is present for interface stability but is
 * usually empty — circle activation stays on the cue clock.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export interface PhraseWordMark {
  tokenIndex: number
  token: string
  /** Milliseconds from the start of the clip. */
  offsetMs: number
}

export interface PhraseAsset {
  cueId: string
  combination: string
  cadence: string
  tokens: string[]
  durationMs: number
  wordMarks: PhraseWordMark[]
  /** Metro module id for the clip. */
  module: number
  renderer: string
}

export const phraseAssets: readonly PhraseAsset[] = [
  {
    cueId: "1-1.technical",
    combination: "1-1",
    cadence: "technical",
    tokens: ["1","1"],
    durationMs: 751,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1.steady",
    combination: "1-1",
    cadence: "steady",
    tokens: ["1","1"],
    durationMs: 698,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1.pressure",
    combination: "1-1",
    cadence: "pressure",
    tokens: ["1","1"],
    durationMs: 608,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1.sprint",
    combination: "1-1",
    cadence: "sprint",
    tokens: ["1","1"],
    durationMs: 465,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.technical",
    combination: "1-1-2",
    cadence: "technical",
    tokens: ["1","1","2"],
    durationMs: 992,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.steady",
    combination: "1-1-2",
    cadence: "steady",
    tokens: ["1","1","2"],
    durationMs: 925,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.pressure",
    combination: "1-1-2",
    cadence: "pressure",
    tokens: ["1","1","2"],
    durationMs: 818,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.sprint",
    combination: "1-1-2",
    cadence: "sprint",
    tokens: ["1","1","2"],
    durationMs: 657,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.technical",
    combination: "1-1-step off",
    cadence: "technical",
    tokens: ["1","1","step off"],
    durationMs: 1490,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.steady",
    combination: "1-1-step off",
    cadence: "steady",
    tokens: ["1","1","step off"],
    durationMs: 1358,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.pressure",
    combination: "1-1-step off",
    cadence: "pressure",
    tokens: ["1","1","step off"],
    durationMs: 1256,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.sprint",
    combination: "1-1-step off",
    cadence: "sprint",
    tokens: ["1","1","step off"],
    durationMs: 994,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2.technical",
    combination: "1-2",
    cadence: "technical",
    tokens: ["1","2"],
    durationMs: 815,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2.steady",
    combination: "1-2",
    cadence: "steady",
    tokens: ["1","2"],
    durationMs: 724,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2.pressure",
    combination: "1-2",
    cadence: "pressure",
    tokens: ["1","2"],
    durationMs: 612,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2.sprint",
    combination: "1-2",
    cadence: "sprint",
    tokens: ["1","2"],
    durationMs: 568,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.technical",
    combination: "1-2-3",
    cadence: "technical",
    tokens: ["1","2","3"],
    durationMs: 1021,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.steady",
    combination: "1-2-3",
    cadence: "steady",
    tokens: ["1","2","3"],
    durationMs: 958,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.pressure",
    combination: "1-2-3",
    cadence: "pressure",
    tokens: ["1","2","3"],
    durationMs: 862,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.sprint",
    combination: "1-2-3",
    cadence: "sprint",
    tokens: ["1","2","3"],
    durationMs: 672,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.technical",
    combination: "1-2-3-2",
    cadence: "technical",
    tokens: ["1","2","3","2"],
    durationMs: 1233,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.steady",
    combination: "1-2-3-2",
    cadence: "steady",
    tokens: ["1","2","3","2"],
    durationMs: 1106,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.pressure",
    combination: "1-2-3-2",
    cadence: "pressure",
    tokens: ["1","2","3","2"],
    durationMs: 1030,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.sprint",
    combination: "1-2-3-2",
    cadence: "sprint",
    tokens: ["1","2","3","2"],
    durationMs: 782,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.technical",
    combination: "1-2-pivot",
    cadence: "technical",
    tokens: ["1","2","pivot"],
    durationMs: 1337,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.steady",
    combination: "1-2-pivot",
    cadence: "steady",
    tokens: ["1","2","pivot"],
    durationMs: 1184,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.pressure",
    combination: "1-2-pivot",
    cadence: "pressure",
    tokens: ["1","2","pivot"],
    durationMs: 1092,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.sprint",
    combination: "1-2-pivot",
    cadence: "sprint",
    tokens: ["1","2","pivot"],
    durationMs: 714,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b.technical",
    combination: "1-2b",
    cadence: "technical",
    tokens: ["1","2b"],
    durationMs: 963,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b.steady",
    combination: "1-2b",
    cadence: "steady",
    tokens: ["1","2b"],
    durationMs: 884,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b.pressure",
    combination: "1-2b",
    cadence: "pressure",
    tokens: ["1","2b"],
    durationMs: 765,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b.sprint",
    combination: "1-2b",
    cadence: "sprint",
    tokens: ["1","2b"],
    durationMs: 594,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.technical",
    combination: "1-2b-3",
    cadence: "technical",
    tokens: ["1","2b","3"],
    durationMs: 1193,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.steady",
    combination: "1-2b-3",
    cadence: "steady",
    tokens: ["1","2b","3"],
    durationMs: 1116,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.pressure",
    combination: "1-2b-3",
    cadence: "pressure",
    tokens: ["1","2b","3"],
    durationMs: 1001,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.sprint",
    combination: "1-2b-3",
    cadence: "sprint",
    tokens: ["1","2b","3"],
    durationMs: 743,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.technical",
    combination: "1-2b-3-2",
    cadence: "technical",
    tokens: ["1","2b","3","2"],
    durationMs: 1428,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.steady",
    combination: "1-2b-3-2",
    cadence: "steady",
    tokens: ["1","2b","3","2"],
    durationMs: 1289,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.pressure",
    combination: "1-2b-3-2",
    cadence: "pressure",
    tokens: ["1","2b","3","2"],
    durationMs: 1155,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.sprint",
    combination: "1-2b-3-2",
    cadence: "sprint",
    tokens: ["1","2b","3","2"],
    durationMs: 925,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.technical",
    combination: "1b-2-3-2",
    cadence: "technical",
    tokens: ["1b","2","3","2"],
    durationMs: 1430,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.steady",
    combination: "1b-2-3-2",
    cadence: "steady",
    tokens: ["1b","2","3","2"],
    durationMs: 1288,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.pressure",
    combination: "1b-2-3-2",
    cadence: "pressure",
    tokens: ["1b","2","3","2"],
    durationMs: 1154,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.sprint",
    combination: "1b-2-3-2",
    cadence: "sprint",
    tokens: ["1b","2","3","2"],
    durationMs: 941,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.technical",
    combination: "2-3-6",
    cadence: "technical",
    tokens: ["2","3","6"],
    durationMs: 1104,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.steady",
    combination: "2-3-6",
    cadence: "steady",
    tokens: ["2","3","6"],
    durationMs: 1002,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.pressure",
    combination: "2-3-6",
    cadence: "pressure",
    tokens: ["2","3","6"],
    durationMs: 843,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.sprint",
    combination: "2-3-6",
    cadence: "sprint",
    tokens: ["2","3","6"],
    durationMs: 717,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.technical",
    combination: "roll-1-2",
    cadence: "technical",
    tokens: ["roll","1","2"],
    durationMs: 1311,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.steady",
    combination: "roll-1-2",
    cadence: "steady",
    tokens: ["roll","1","2"],
    durationMs: 1250,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.pressure",
    combination: "roll-1-2",
    cadence: "pressure",
    tokens: ["roll","1","2"],
    durationMs: 1118,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.sprint",
    combination: "roll-1-2",
    cadence: "sprint",
    tokens: ["roll","1","2"],
    durationMs: 1029,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.technical",
    combination: "roll-3-2",
    cadence: "technical",
    tokens: ["roll","3","2"],
    durationMs: 1457,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.steady",
    combination: "roll-3-2",
    cadence: "steady",
    tokens: ["roll","3","2"],
    durationMs: 1340,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.pressure",
    combination: "roll-3-2",
    cadence: "pressure",
    tokens: ["roll","3","2"],
    durationMs: 1149,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.sprint",
    combination: "roll-3-2",
    cadence: "sprint",
    tokens: ["roll","3","2"],
    durationMs: 1061,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.technical",
    combination: "slip-1-2",
    cadence: "technical",
    tokens: ["slip","1","2"],
    durationMs: 1332,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.steady",
    combination: "slip-1-2",
    cadence: "steady",
    tokens: ["slip","1","2"],
    durationMs: 1197,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.pressure",
    combination: "slip-1-2",
    cadence: "pressure",
    tokens: ["slip","1","2"],
    durationMs: 1061,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.sprint",
    combination: "slip-1-2",
    cadence: "sprint",
    tokens: ["slip","1","2"],
    durationMs: 1014,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.technical",
    combination: "slip-2-3-2",
    cadence: "technical",
    tokens: ["slip","2","3","2"],
    durationMs: 1651,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.technical.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.steady",
    combination: "slip-2-3-2",
    cadence: "steady",
    tokens: ["slip","2","3","2"],
    durationMs: 1473,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.steady.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.pressure",
    combination: "slip-2-3-2",
    cadence: "pressure",
    tokens: ["slip","2","3","2"],
    durationMs: 1256,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.pressure.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.sprint",
    combination: "slip-2-3-2",
    cadence: "sprint",
    tokens: ["slip","2","3","2"],
    durationMs: 1170,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.sprint.wav'),
    renderer: "kokoro-aged-melodic-theatrical-broadcast",
  },
]

/* eslint-enable @typescript-eslint/no-require-imports */

/** Lookup by combination and cadence. */
export function findPhraseAsset(
  combination: string,
  cadence: string,
): PhraseAsset | undefined {
  return phraseAssets.find((a) => a.combination === combination && a.cadence === cadence)
}
