/**
 * Whole-phrase combination assets (generated).
 *
 * DO NOT EDIT — produced by `node tools/voice/make-phrase-clips.mjs`.
 *
 * Each entry pairs a clip with the word offsets the synthesizer itself
 * reported, so the live screen can light a circle at the moment its number
 * is spoken rather than inferring it from an amplitude envelope.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export interface PhraseWordMark {
  tokenIndex: number
  token: string
  /** Milliseconds from the start of the clip. */
  offsetMs: number
}

export interface PhraseAsset {
  cueId: string
  combination: string
  cadence: string
  tokens: string[]
  durationMs: number
  wordMarks: PhraseWordMark[]
  /** Metro module id for the clip. */
  module: number
  renderer: string
}

export const phraseAssets: readonly PhraseAsset[] = [
  {
    cueId: "1-1.technical",
    combination: "1-1",
    cadence: "technical",
    tokens: ["1","1"],
    durationMs: 751,
    wordMarks: [{"tokenIndex":0,"token":"1","offsetMs":0},{"tokenIndex":1,"token":"1","offsetMs":702}],
    module: require('../../../assets/voice/phrases/1-1.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1.steady",
    combination: "1-1",
    cadence: "steady",
    tokens: ["1","1"],
    durationMs: 637,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1.pressure",
    combination: "1-1",
    cadence: "pressure",
    tokens: ["1","1"],
    durationMs: 581,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1.sprint",
    combination: "1-1",
    cadence: "sprint",
    tokens: ["1","1"],
    durationMs: 497,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-2.technical",
    combination: "1-1-2",
    cadence: "technical",
    tokens: ["1","1","2"],
    durationMs: 1010,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-2.steady",
    combination: "1-1-2",
    cadence: "steady",
    tokens: ["1","1","2"],
    durationMs: 920,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-2.pressure",
    combination: "1-1-2",
    cadence: "pressure",
    tokens: ["1","1","2"],
    durationMs: 807,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-2.sprint",
    combination: "1-1-2",
    cadence: "sprint",
    tokens: ["1","1","2"],
    durationMs: 650,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-step off.technical",
    combination: "1-1-step off",
    cadence: "technical",
    tokens: ["1","1","step off"],
    durationMs: 1257,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-step off.steady",
    combination: "1-1-step off",
    cadence: "steady",
    tokens: ["1","1","step off"],
    durationMs: 1189,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-step off.pressure",
    combination: "1-1-step off",
    cadence: "pressure",
    tokens: ["1","1","step off"],
    durationMs: 1034,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-1-step off.sprint",
    combination: "1-1-step off",
    cadence: "sprint",
    tokens: ["1","1","step off"],
    durationMs: 808,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2.technical",
    combination: "1-2",
    cadence: "technical",
    tokens: ["1","2"],
    durationMs: 839,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2.steady",
    combination: "1-2",
    cadence: "steady",
    tokens: ["1","2"],
    durationMs: 697,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2.pressure",
    combination: "1-2",
    cadence: "pressure",
    tokens: ["1","2"],
    durationMs: 665,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2.sprint",
    combination: "1-2",
    cadence: "sprint",
    tokens: ["1","2"],
    durationMs: 583,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3.technical",
    combination: "1-2-3",
    cadence: "technical",
    tokens: ["1","2","3"],
    durationMs: 1067,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3.steady",
    combination: "1-2-3",
    cadence: "steady",
    tokens: ["1","2","3"],
    durationMs: 960,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3.pressure",
    combination: "1-2-3",
    cadence: "pressure",
    tokens: ["1","2","3"],
    durationMs: 869,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3.sprint",
    combination: "1-2-3",
    cadence: "sprint",
    tokens: ["1","2","3"],
    durationMs: 712,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3-2.technical",
    combination: "1-2-3-2",
    cadence: "technical",
    tokens: ["1","2","3","2"],
    durationMs: 1287,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3-2.steady",
    combination: "1-2-3-2",
    cadence: "steady",
    tokens: ["1","2","3","2"],
    durationMs: 1134,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3-2.pressure",
    combination: "1-2-3-2",
    cadence: "pressure",
    tokens: ["1","2","3","2"],
    durationMs: 1013,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-3-2.sprint",
    combination: "1-2-3-2",
    cadence: "sprint",
    tokens: ["1","2","3","2"],
    durationMs: 803,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-pivot.technical",
    combination: "1-2-pivot",
    cadence: "technical",
    tokens: ["1","2","pivot"],
    durationMs: 1041,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-pivot.steady",
    combination: "1-2-pivot",
    cadence: "steady",
    tokens: ["1","2","pivot"],
    durationMs: 960,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-pivot.pressure",
    combination: "1-2-pivot",
    cadence: "pressure",
    tokens: ["1","2","pivot"],
    durationMs: 864,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2-pivot.sprint",
    combination: "1-2-pivot",
    cadence: "sprint",
    tokens: ["1","2","pivot"],
    durationMs: 689,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b.technical",
    combination: "1-2b",
    cadence: "technical",
    tokens: ["1","2b"],
    durationMs: 1128,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b.steady",
    combination: "1-2b",
    cadence: "steady",
    tokens: ["1","2b"],
    durationMs: 946,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b.pressure",
    combination: "1-2b",
    cadence: "pressure",
    tokens: ["1","2b"],
    durationMs: 856,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b.sprint",
    combination: "1-2b",
    cadence: "sprint",
    tokens: ["1","2b"],
    durationMs: 754,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3.technical",
    combination: "1-2b-3",
    cadence: "technical",
    tokens: ["1","2b","3"],
    durationMs: 1349,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3.steady",
    combination: "1-2b-3",
    cadence: "steady",
    tokens: ["1","2b","3"],
    durationMs: 1191,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3.pressure",
    combination: "1-2b-3",
    cadence: "pressure",
    tokens: ["1","2b","3"],
    durationMs: 1100,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3.sprint",
    combination: "1-2b-3",
    cadence: "sprint",
    tokens: ["1","2b","3"],
    durationMs: 930,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3-2.technical",
    combination: "1-2b-3-2",
    cadence: "technical",
    tokens: ["1","2b","3","2"],
    durationMs: 1572,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3-2.steady",
    combination: "1-2b-3-2",
    cadence: "steady",
    tokens: ["1","2b","3","2"],
    durationMs: 1412,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3-2.pressure",
    combination: "1-2b-3-2",
    cadence: "pressure",
    tokens: ["1","2b","3","2"],
    durationMs: 1277,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1-2b-3-2.sprint",
    combination: "1-2b-3-2",
    cadence: "sprint",
    tokens: ["1","2b","3","2"],
    durationMs: 1003,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1b-2-3-2.technical",
    combination: "1b-2-3-2",
    cadence: "technical",
    tokens: ["1b","2","3","2"],
    durationMs: 1551,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1b-2-3-2.steady",
    combination: "1b-2-3-2",
    cadence: "steady",
    tokens: ["1b","2","3","2"],
    durationMs: 1367,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1b-2-3-2.pressure",
    combination: "1b-2-3-2",
    cadence: "pressure",
    tokens: ["1b","2","3","2"],
    durationMs: 1216,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "1b-2-3-2.sprint",
    combination: "1b-2-3-2",
    cadence: "sprint",
    tokens: ["1b","2","3","2"],
    durationMs: 942,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "2-3-6.technical",
    combination: "2-3-6",
    cadence: "technical",
    tokens: ["2","3","6"],
    durationMs: 1118,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "2-3-6.steady",
    combination: "2-3-6",
    cadence: "steady",
    tokens: ["2","3","6"],
    durationMs: 1016,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "2-3-6.pressure",
    combination: "2-3-6",
    cadence: "pressure",
    tokens: ["2","3","6"],
    durationMs: 875,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "2-3-6.sprint",
    combination: "2-3-6",
    cadence: "sprint",
    tokens: ["2","3","6"],
    durationMs: 699,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-1-2.technical",
    combination: "roll-1-2",
    cadence: "technical",
    tokens: ["roll","1","2"],
    durationMs: 1032,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-1-2.steady",
    combination: "roll-1-2",
    cadence: "steady",
    tokens: ["roll","1","2"],
    durationMs: 963,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-1-2.pressure",
    combination: "roll-1-2",
    cadence: "pressure",
    tokens: ["roll","1","2"],
    durationMs: 804,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-1-2.sprint",
    combination: "roll-1-2",
    cadence: "sprint",
    tokens: ["roll","1","2"],
    durationMs: 708,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-3-2.technical",
    combination: "roll-3-2",
    cadence: "technical",
    tokens: ["roll","3","2"],
    durationMs: 1145,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-3-2.steady",
    combination: "roll-3-2",
    cadence: "steady",
    tokens: ["roll","3","2"],
    durationMs: 1003,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-3-2.pressure",
    combination: "roll-3-2",
    cadence: "pressure",
    tokens: ["roll","3","2"],
    durationMs: 865,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "roll-3-2.sprint",
    combination: "roll-3-2",
    cadence: "sprint",
    tokens: ["roll","3","2"],
    durationMs: 739,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-1-2.technical",
    combination: "slip-1-2",
    cadence: "technical",
    tokens: ["slip","1","2"],
    durationMs: 1108,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-1-2.steady",
    combination: "slip-1-2",
    cadence: "steady",
    tokens: ["slip","1","2"],
    durationMs: 1013,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-1-2.pressure",
    combination: "slip-1-2",
    cadence: "pressure",
    tokens: ["slip","1","2"],
    durationMs: 837,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-1-2.sprint",
    combination: "slip-1-2",
    cadence: "sprint",
    tokens: ["slip","1","2"],
    durationMs: 736,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-2-3-2.technical",
    combination: "slip-2-3-2",
    cadence: "technical",
    tokens: ["slip","2","3","2"],
    durationMs: 1329,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.technical.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-2-3-2.steady",
    combination: "slip-2-3-2",
    cadence: "steady",
    tokens: ["slip","2","3","2"],
    durationMs: 1213,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.steady.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-2-3-2.pressure",
    combination: "slip-2-3-2",
    cadence: "pressure",
    tokens: ["slip","2","3","2"],
    durationMs: 1033,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.pressure.wav'),
    renderer: "kokoro-am_michael",
  },
  {
    cueId: "slip-2-3-2.sprint",
    combination: "slip-2-3-2",
    cadence: "sprint",
    tokens: ["slip","2","3","2"],
    durationMs: 867,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.sprint.wav'),
    renderer: "kokoro-am_michael",
  },
]

/* eslint-enable @typescript-eslint/no-require-imports */

/** Lookup by combination and cadence. */
export function findPhraseAsset(
  combination: string,
  cadence: string,
): PhraseAsset | undefined {
  return phraseAssets.find((a) => a.combination === combination && a.cadence === cadence)
}
