/**
 * Whole-phrase combination assets (generated).
 *
 * DO NOT EDIT — produced by `node tools/voice/make-phrase-clips.mjs`.
 *
 * One clip per (combination, cadence), spoken by the settled Old-School
 * Cornerman persona. `wordMarks` is present for interface stability but is
 * usually empty — circle activation stays on the cue clock.
 */

/* eslint-disable @typescript-eslint/no-require-imports */

export interface PhraseWordMark {
  tokenIndex: number
  token: string
  /** Milliseconds from the start of the clip. */
  offsetMs: number
}

export interface PhraseAsset {
  cueId: string
  combination: string
  cadence: string
  tokens: string[]
  durationMs: number
  wordMarks: PhraseWordMark[]
  /** Metro module id for the clip. */
  module: number
  renderer: string
}

export const phraseAssets: readonly PhraseAsset[] = [
  {
    cueId: "1-1.technical",
    combination: "1-1",
    cadence: "technical",
    tokens: ["1","1"],
    durationMs: 845,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1.steady",
    combination: "1-1",
    cadence: "steady",
    tokens: ["1","1"],
    durationMs: 762,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1.pressure",
    combination: "1-1",
    cadence: "pressure",
    tokens: ["1","1"],
    durationMs: 629,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1.sprint",
    combination: "1-1",
    cadence: "sprint",
    tokens: ["1","1"],
    durationMs: 582,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.technical",
    combination: "1-1-2",
    cadence: "technical",
    tokens: ["1","1","2"],
    durationMs: 1121,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.steady",
    combination: "1-1-2",
    cadence: "steady",
    tokens: ["1","1","2"],
    durationMs: 1015,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.pressure",
    combination: "1-1-2",
    cadence: "pressure",
    tokens: ["1","1","2"],
    durationMs: 891,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-2.sprint",
    combination: "1-1-2",
    cadence: "sprint",
    tokens: ["1","1","2"],
    durationMs: 757,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.technical",
    combination: "1-1-step off",
    cadence: "technical",
    tokens: ["1","1","step off"],
    durationMs: 1448,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.steady",
    combination: "1-1-step off",
    cadence: "steady",
    tokens: ["1","1","step off"],
    durationMs: 1337,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.pressure",
    combination: "1-1-step off",
    cadence: "pressure",
    tokens: ["1","1","step off"],
    durationMs: 1218,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-1-step off.sprint",
    combination: "1-1-step off",
    cadence: "sprint",
    tokens: ["1","1","step off"],
    durationMs: 830,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-1-step off.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2.technical",
    combination: "1-2",
    cadence: "technical",
    tokens: ["1","2"],
    durationMs: 961,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2.steady",
    combination: "1-2",
    cadence: "steady",
    tokens: ["1","2"],
    durationMs: 850,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2.pressure",
    combination: "1-2",
    cadence: "pressure",
    tokens: ["1","2"],
    durationMs: 708,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2.sprint",
    combination: "1-2",
    cadence: "sprint",
    tokens: ["1","2"],
    durationMs: 649,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.technical",
    combination: "1-2-3",
    cadence: "technical",
    tokens: ["1","2","3"],
    durationMs: 1185,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.steady",
    combination: "1-2-3",
    cadence: "steady",
    tokens: ["1","2","3"],
    durationMs: 1053,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.pressure",
    combination: "1-2-3",
    cadence: "pressure",
    tokens: ["1","2","3"],
    durationMs: 941,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3.sprint",
    combination: "1-2-3",
    cadence: "sprint",
    tokens: ["1","2","3"],
    durationMs: 740,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.technical",
    combination: "1-2-3-2",
    cadence: "technical",
    tokens: ["1","2","3","2"],
    durationMs: 1448,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.steady",
    combination: "1-2-3-2",
    cadence: "steady",
    tokens: ["1","2","3","2"],
    durationMs: 1290,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.pressure",
    combination: "1-2-3-2",
    cadence: "pressure",
    tokens: ["1","2","3","2"],
    durationMs: 1106,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-3-2.sprint",
    combination: "1-2-3-2",
    cadence: "sprint",
    tokens: ["1","2","3","2"],
    durationMs: 928,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-3-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.technical",
    combination: "1-2-pivot",
    cadence: "technical",
    tokens: ["1","2","pivot"],
    durationMs: 1380,
    wordMarks: [{"tokenIndex":0,"token":"1","offsetMs":20},{"tokenIndex":1,"token":"2","offsetMs":810},{"tokenIndex":2,"token":"pivot","offsetMs":1190}],
    module: require('../../../assets/voice/phrases/1-2-pivot.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.steady",
    combination: "1-2-pivot",
    cadence: "steady",
    tokens: ["1","2","pivot"],
    durationMs: 1284,
    wordMarks: [{"tokenIndex":0,"token":"1","offsetMs":20},{"tokenIndex":1,"token":"2","offsetMs":780},{"tokenIndex":2,"token":"pivot","offsetMs":1150}],
    module: require('../../../assets/voice/phrases/1-2-pivot.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.pressure",
    combination: "1-2-pivot",
    cadence: "pressure",
    tokens: ["1","2","pivot"],
    durationMs: 1095,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2-pivot.sprint",
    combination: "1-2-pivot",
    cadence: "sprint",
    tokens: ["1","2","pivot"],
    durationMs: 778,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2-pivot.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b.technical",
    combination: "1-2b",
    cadence: "technical",
    tokens: ["1","2b"],
    durationMs: 1126,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b.steady",
    combination: "1-2b",
    cadence: "steady",
    tokens: ["1","2b"],
    durationMs: 993,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b.pressure",
    combination: "1-2b",
    cadence: "pressure",
    tokens: ["1","2b"],
    durationMs: 860,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b.sprint",
    combination: "1-2b",
    cadence: "sprint",
    tokens: ["1","2b"],
    durationMs: 754,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.technical",
    combination: "1-2b-3",
    cadence: "technical",
    tokens: ["1","2b","3"],
    durationMs: 1381,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.steady",
    combination: "1-2b-3",
    cadence: "steady",
    tokens: ["1","2b","3"],
    durationMs: 1212,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.pressure",
    combination: "1-2b-3",
    cadence: "pressure",
    tokens: ["1","2b","3"],
    durationMs: 1085,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3.sprint",
    combination: "1-2b-3",
    cadence: "sprint",
    tokens: ["1","2b","3"],
    durationMs: 859,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.technical",
    combination: "1-2b-3-2",
    cadence: "technical",
    tokens: ["1","2b","3","2"],
    durationMs: 1636,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.steady",
    combination: "1-2b-3-2",
    cadence: "steady",
    tokens: ["1","2b","3","2"],
    durationMs: 1481,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.pressure",
    combination: "1-2b-3-2",
    cadence: "pressure",
    tokens: ["1","2b","3","2"],
    durationMs: 1249,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1-2b-3-2.sprint",
    combination: "1-2b-3-2",
    cadence: "sprint",
    tokens: ["1","2b","3","2"],
    durationMs: 1040,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1-2b-3-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.technical",
    combination: "1b-2-3-2",
    cadence: "technical",
    tokens: ["1b","2","3","2"],
    durationMs: 1640,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.steady",
    combination: "1b-2-3-2",
    cadence: "steady",
    tokens: ["1b","2","3","2"],
    durationMs: 1457,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.pressure",
    combination: "1b-2-3-2",
    cadence: "pressure",
    tokens: ["1b","2","3","2"],
    durationMs: 1274,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "1b-2-3-2.sprint",
    combination: "1b-2-3-2",
    cadence: "sprint",
    tokens: ["1b","2","3","2"],
    durationMs: 1040,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/1b-2-3-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.technical",
    combination: "2-3-6",
    cadence: "technical",
    tokens: ["2","3","6"],
    durationMs: 1238,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.steady",
    combination: "2-3-6",
    cadence: "steady",
    tokens: ["2","3","6"],
    durationMs: 1119,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.pressure",
    combination: "2-3-6",
    cadence: "pressure",
    tokens: ["2","3","6"],
    durationMs: 942,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "2-3-6.sprint",
    combination: "2-3-6",
    cadence: "sprint",
    tokens: ["2","3","6"],
    durationMs: 797,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/2-3-6.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.technical",
    combination: "roll-1-2",
    cadence: "technical",
    tokens: ["roll","1","2"],
    durationMs: 1429,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.steady",
    combination: "roll-1-2",
    cadence: "steady",
    tokens: ["roll","1","2"],
    durationMs: 1264,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.pressure",
    combination: "roll-1-2",
    cadence: "pressure",
    tokens: ["roll","1","2"],
    durationMs: 1152,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-1-2.sprint",
    combination: "roll-1-2",
    cadence: "sprint",
    tokens: ["roll","1","2"],
    durationMs: 1066,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-1-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.technical",
    combination: "roll-3-2",
    cadence: "technical",
    tokens: ["roll","3","2"],
    durationMs: 1529,
    wordMarks: [{"tokenIndex":0,"token":"roll","offsetMs":20},{"tokenIndex":1,"token":"3","offsetMs":710},{"tokenIndex":2,"token":"2","offsetMs":1000}],
    module: require('../../../assets/voice/phrases/roll-3-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.steady",
    combination: "roll-3-2",
    cadence: "steady",
    tokens: ["roll","3","2"],
    durationMs: 1362,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.pressure",
    combination: "roll-3-2",
    cadence: "pressure",
    tokens: ["roll","3","2"],
    durationMs: 1196,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "roll-3-2.sprint",
    combination: "roll-3-2",
    cadence: "sprint",
    tokens: ["roll","3","2"],
    durationMs: 1112,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/roll-3-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.technical",
    combination: "slip-1-2",
    cadence: "technical",
    tokens: ["slip","1","2"],
    durationMs: 1433,
    wordMarks: [{"tokenIndex":0,"token":"slip","offsetMs":0},{"tokenIndex":1,"token":"1","offsetMs":340},{"tokenIndex":2,"token":"2","offsetMs":890}],
    module: require('../../../assets/voice/phrases/slip-1-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.steady",
    combination: "slip-1-2",
    cadence: "steady",
    tokens: ["slip","1","2"],
    durationMs: 1336,
    wordMarks: [{"tokenIndex":0,"token":"slip","offsetMs":0},{"tokenIndex":1,"token":"1","offsetMs":310},{"tokenIndex":2,"token":"2","offsetMs":850}],
    module: require('../../../assets/voice/phrases/slip-1-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.pressure",
    combination: "slip-1-2",
    cadence: "pressure",
    tokens: ["slip","1","2"],
    durationMs: 1175,
    wordMarks: [{"tokenIndex":0,"token":"slip","offsetMs":10},{"tokenIndex":1,"token":"1","offsetMs":260},{"tokenIndex":2,"token":"2","offsetMs":740}],
    module: require('../../../assets/voice/phrases/slip-1-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-1-2.sprint",
    combination: "slip-1-2",
    cadence: "sprint",
    tokens: ["slip","1","2"],
    durationMs: 1058,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-1-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.technical",
    combination: "slip-2-3-2",
    cadence: "technical",
    tokens: ["slip","2","3","2"],
    durationMs: 1718,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.technical.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.steady",
    combination: "slip-2-3-2",
    cadence: "steady",
    tokens: ["slip","2","3","2"],
    durationMs: 1587,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.steady.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.pressure",
    combination: "slip-2-3-2",
    cadence: "pressure",
    tokens: ["slip","2","3","2"],
    durationMs: 1345,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.pressure.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
  {
    cueId: "slip-2-3-2.sprint",
    combination: "slip-2-3-2",
    cadence: "sprint",
    tokens: ["slip","2","3","2"],
    durationMs: 1167,
    wordMarks: [],
    module: require('../../../assets/voice/phrases/slip-2-3-2.sprint.wav'),
    renderer: "kokoro-stone-theatrical-broadcast",
  },
]

/* eslint-enable @typescript-eslint/no-require-imports */

/** Lookup by combination and cadence. */
export function findPhraseAsset(
  combination: string,
  cadence: string,
): PhraseAsset | undefined {
  return phraseAssets.find((a) => a.combination === combination && a.cadence === cadence)
}
