/**
 * Inter-round recovery walkthroughs (generated from tools/voice/recovery.json).
 *
 * PLACEHOLDER: this file is regenerated by
 * `node tools/voice/make-recovery-clips.mjs` after the render batch
 * finishes. The empty array keeps tsc/lint green while the GPU renders;
 * the live wiring's find/lookup just returns nothing until the real
 * manifest replaces it, which means the rest still runs — silently.
 *
 * DO NOT EDIT — regenerate with `node tools/voice/make-recovery-clips.mjs`.
 */

export interface RecoverySegmentClip {
  module: number
  durationMs: number
  pauseAfterMs: number
}

export interface RecoveryScript {
  scriptId: string
  title: string
  category: string
  tags: readonly string[]
  hydrationPrompt: boolean
  requiresStableBag: boolean
  avoidIfDizzy: boolean
  segments: readonly RecoverySegmentClip[]
  measuredTotalMs: number
  corpusVersion: string
}

export const RECOVERY_SCRIPTS: readonly RecoveryScript[] = []
